# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('cognitive', ['core', 'network'])
    module.source = [
        'model/repository.cc',
        'model/PUmodel.cc',
        'model/SpectrumData.cc',
        'model/SpectrumTimer.cc',
        'model/SpectrumManager.cc',
        'model/SpectrumDecision.cc',
        'model/SpectrumMobility.cc',
        'model/SpectrumSensing.cc',
#        'helper/cognitive-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('cognitive')
    module_test.source = [
        'test/cognitive-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'cognitive'
    headers.source = [
        'model/repository.h',
        'model/PUmodel.h',
        'model/SpectrumData.h',
        'model/SpectrumTimer.h',
        'model/SpectrumManager.h',
        'model/SpectrumDecision.h',
        'model/SpectrumMobility.h',
        'model/SpectrumSensing.h',
        'model/commCognitiveHeader.h',
#        'helper/cognitive-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

